name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-linux-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-linux-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Show contents
        run: ls -lh target/release

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/release/docx-cleaner dist/docx-cleaner-linux-x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/docx-cleaner-linux-x86_64

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-windows-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-windows-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Build binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Show contents
        run: Get-ChildItem target\x86_64-pc-windows-msvc\release

      - name: Prepare artifact
        run: |
          mkdir dist
          copy target\x86_64-pc-windows-msvc\release\docx-cleaner.exe dist\docx-cleaner-windows-x86_64.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/docx-cleaner-windows-x86_64.exe

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: dist

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/docx-cleaner-linux-x86_64
            dist/docx-cleaner-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
