name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: List release files
        run: ls -lh target/release

      - name: Prepare release artifact
        run: |
          mkdir -p dist
          cp target/release/docx_cleaner dist/docx_cleaner-linux-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/docx_cleaner-linux-x86_64

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Build binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: List release files
        run: Get-ChildItem target\x86_64-pc-windows-msvc\release

      - name: Prepare release artifact
        run: |
          mkdir dist
          copy target\x86_64-pc-windows-msvc\release\docx_cleaner.exe dist\docx_cleaner-windows-x86_64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/docx_cleaner-windows-x86_64.exe

  release:
    name: Create GitHub Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux binary
        uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: dist

      - name: Download Windows binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/docx_cleaner-linux-x86_64
            dist/docx_cleaner-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
